import { useCallback, useEffect, useState } from 'react';
import { Check, Clock3, ShieldAlert, X } from 'lucide-react';
import { GlassCard } from '@/components/ui';
import { useAuth } from '@/contexts/AuthContext';
import { useWorkspace } from '@/hooks/useWorkspace';
import { supabase } from '@/lib/supabase';
import type { ApprovalRequest } from '@/types/platform';

export default function ApprovalsPage(){
 const {user}=useAuth(); const {organization,role}=useWorkspace(); const [items,setItems]=useState<ApprovalRequest[]>([]); const [busy,setBusy]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!organization)return;const {data}=await supabase.from('approval_requests').select('id,action_type,risk_level,status,action_preview,expires_at,created_at').eq('organization_id',organization.id).order('created_at',{ascending:false});setItems((data??[]) as ApprovalRequest[])},[organization]);
 useEffect(()=>{void load()},[load]);
 const decide=async(item:ApprovalRequest,status:'approved'|'rejected')=>{if(!user||!['owner','admin'].includes(role??''))return;setBusy(item.id);const now=new Date();if(new Date(item.expires_at)<=now){await supabase.from('approval_requests').update({status:'expired'}).eq('id',item.id).eq('status','pending')}else{await supabase.from('approval_requests').update({status,decided_by:user.id,decided_at:now.toISOString()}).eq('id',item.id).eq('status','pending')}setBusy(null);await load()};
 return <div className="p-5 md:p-8 max-w-5xl mx-auto"><header className="mb-7"><p className="text-xs uppercase tracking-[.2em] text-gray-500">Human control</p><h1 className="text-3xl text-white mt-2">Approvals</h1><p className="text-sm text-gray-500 mt-2">Review the exact action Pandora intends to execute.</p></header><div className="space-y-4">{items.length?items.map(item=><GlassCard key={item.id} hover={false} className="p-6"><div className="flex flex-col md:flex-row md:items-start justify-between gap-5"><div className="min-w-0"><div className="flex items-center gap-2"><ShieldAlert size={17} className={item.risk_level==='high'?'text-red-400':'text-amber-300'}/><h2 className="text-lg text-white capitalize">{item.action_type.replaceAll('_',' ')}</h2><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase text-gray-400">{item.status}</span></div><pre className="mt-4 whitespace-pre-wrap break-words rounded-2xl bg-black/40 border border-white/7 p-4 text-xs text-gray-400 font-mono">{JSON.stringify(item.action_preview,null,2)}</pre><p className="mt-3 text-xs text-gray-600 flex items-center gap-1"><Clock3 size={12}/> Expires {new Date(item.expires_at).toLocaleString()}</p></div>{item.status==='pending'&&<div className="flex gap-2 shrink-0"><button disabled={busy===item.id} onClick={()=>void decide(item,'rejected')} className="inline-flex items-center gap-2 rounded-full border border-white/12 px-4 py-2 text-sm text-gray-300 hover:bg-white/5"><X size={14}/>Reject</button><button disabled={busy===item.id} onClick={()=>void decide(item,'approved')} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-semibold text-black"><Check size={14}/>Approve</button></div>}</div></GlassCard>):<div className="rounded-3xl border border-white/8 py-20 text-center text-sm text-gray-600">No approval requests yet.</div>}</div></div>
}
