import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, CalendarCheck2, Check, FileText, Mail, Menu, Mic, Phone, Receipt, ShieldCheck, Sparkles, X } from 'lucide-react';
import { PlaceholderLogo } from '@/components/ui';

const capabilities=[
 {icon:Mail,title:'Email operations',copy:'Find messages, prepare replies and send only after you approve the exact recipient and content.'},
 {icon:CalendarCheck2,title:'Scheduling',copy:'Capture attendee emails, timezone, duration and conflicts before creating a Google Meet.'},
 {icon:Phone,title:'Phone access',copy:'Reach Pandora from an ordinary phone—even when you do not have mobile data or a smartphone.'},
 {icon:Receipt,title:'Invoices and reports',copy:'Draft invoices, payment reminders and bookkeeping summaries without silently moving money.'},
 {icon:FileText,title:'Business knowledge',copy:'Answer customer questions from the knowledge base configured for your organization.'},
 {icon:ShieldCheck,title:'Human control',copy:'Every risky action is previewed, confirmed and written to an audit trail in your dashboard.'},
];
const plans=[['Free','₦0','Web chat, 15 web-voice minutes, tasks and reminders'],['Solo','₦29,900','Google Workspace actions, 100 voice minutes and reports'],['Business','₦79,900','Team approvals, 400 voice minutes and messaging channels'],['Scale','₦199,900','Dedicated SIP onboarding, 1,200 minutes and priority support']];

export default function LandingPage(){const [menu,setMenu]=useState(false);const [step,setStep]=useState(0);const demo=[['You','Schedule a Google Meet with Amina next Tuesday afternoon.'],['Pandora','What email address should I invite, and should I use 2:00 PM Africa/Lagos?'],['You','amina@acme.ng. Yes, make it 30 minutes.'],['Pandora','I found no conflict. Shall I create “Meeting with Amina” for Tuesday at 2:00 PM and invite amina@acme.ng?']];return <div className="min-h-screen bg-[#050505] text-white overflow-hidden"><nav className="fixed top-0 inset-x-0 z-50 border-b border-white/6 bg-black/70 backdrop-blur-xl"><div className="max-w-7xl mx-auto px-5 md:px-8 h-16 flex items-center justify-between"><Link to="/" className="flex items-center gap-3"><PlaceholderLogo size={33}/><span className="font-semibold tracking-tight">Pandora <span className="text-gray-500">Labs</span></span></Link><div className="hidden md:flex items-center gap-7 text-sm text-gray-400"><a href="#capabilities" className="hover:text-white">What it does</a><a href="#trust" className="hover:text-white">Trust</a><a href="#pricing" className="hover:text-white">Pricing</a><Link to="/login" className="hover:text-white">Sign in</Link><Link to="/signup" className="rounded-full bg-white text-black px-5 py-2.5 font-semibold">Start free</Link></div><button className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="md:hidden border-t border-white/5 px-5 py-5 space-y-4 bg-black"><a href="#capabilities" onClick={()=>setMenu(false)} className="block text-gray-300">What it does</a><a href="#pricing" onClick={()=>setMenu(false)} className="block text-gray-300">Pricing</a><Link to="/signup" className="block rounded-full bg-white text-black px-5 py-3 text-center font-semibold">Start free</Link></div>}</nav>

<main><section className="relative min-h-[92vh] flex items-center pt-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_68%_35%,rgba(255,255,255,.09),transparent_27%)]"/><img src="/images/hero_character.png" alt="Pandora voice agent" className="absolute right-[-8%] bottom-0 w-[65%] max-w-[880px] h-[86%] object-contain object-bottom grayscale opacity-50 mix-blend-lighten hidden lg:block"/><div className="relative max-w-7xl mx-auto px-5 md:px-8 w-full"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-4 py-2 text-xs text-gray-400"><Sparkles size={13}/> Voice-first business operations, built for Nigeria</div><h1 className="mt-7 text-[clamp(3.3rem,8vw,7.5rem)] font-light tracking-[-.065em] leading-[.88]">Your business<br/><span className="text-gray-500">can answer back.</span></h1><p className="mt-7 max-w-xl text-base md:text-lg leading-relaxed text-gray-400">Pandora answers customers, schedules meetings, handles email, prepares invoices and keeps you in control—from the web or an ordinary phone call.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/signup" className="inline-flex items-center gap-2 rounded-full bg-white text-black px-6 py-3.5 text-sm font-semibold">Build your workspace <ArrowRight size={16}/></Link><a href="#demo" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 text-sm text-white"><Mic size={16}/> See a call unfold</a></div><p className="mt-5 text-xs text-gray-600">No card required. Free web voice included. Phone access is cloud-powered and works without mobile data.</p></div></div></section>

<section className="border-y border-white/6 bg-[#080808]"><div className="max-w-7xl mx-auto px-5 md:px-8 py-6 grid grid-cols-2 md:grid-cols-4 gap-6 text-center"><Proof value="One agent" label="Across web and phone"/><Proof value="One workflow" label="Across every customer"/><Proof value="Human approval" label="Before risky actions"/><Proof value="Supabase" label="For the full audit trail"/></div></section>

<section id="demo" className="max-w-7xl mx-auto px-5 md:px-8 py-24 md:py-32 grid lg:grid-cols-[.8fr_1.2fr] gap-12 items-center"><div><p className="eyebrow">Intelligent clarification</p><h2 className="section-title">It knows when not to guess.</h2><p className="section-copy">Names, email addresses and Nigerian date expressions can be ambiguous. Pandora asks one useful question at a time, reads the final action back, then waits for confirmation.</p><button onClick={()=>setStep((step+1)%demo.length)} className="mt-7 rounded-full border border-white/15 px-5 py-3 text-sm hover:bg-white/5">Advance conversation</button></div><div className="rounded-[30px] border border-white/10 bg-[#090909] p-5 md:p-7 shadow-2xl"><div className="flex items-center justify-between border-b border-white/6 pb-5"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-white text-black flex items-center justify-center"><Mic size={17}/></div><div><p className="text-sm">Pandora phone session</p><p className="text-xs text-emerald-400 mt-1">Listening securely</p></div></div><span className="text-xs text-gray-600">02:14</span></div><div className="py-6 space-y-4 min-h-[360px]">{demo.slice(0,step+1).map(([speaker,text],i)=><motion.div key={i} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className={`max-w-[85%] rounded-2xl p-4 text-sm leading-relaxed ${speaker==='You'?'ml-auto bg-white text-black rounded-br-sm':'bg-white/[.04] border border-white/8 text-gray-300 rounded-bl-sm'}`}><p className={`text-[10px] uppercase tracking-wider mb-2 ${speaker==='You'?'text-black/50':'text-gray-600'}`}>{speaker}</p>{text}</motion.div>)}</div><div className="rounded-2xl bg-amber-400/5 border border-amber-300/10 p-4 flex gap-3"><ShieldCheck size={16} className="text-amber-300 shrink-0"/><p className="text-xs text-gray-400">No calendar event exists until the owner confirms the complete preview.</p></div></div></section>

<section id="capabilities" className="bg-[#080808] border-y border-white/6 py-24 md:py-32"><div className="max-w-7xl mx-auto px-5 md:px-8"><p className="eyebrow">One operating layer</p><div className="flex flex-col md:flex-row md:items-end justify-between gap-6"><h2 className="section-title max-w-3xl">The work around the work,<br/>handled by voice.</h2><p className="section-copy max-w-md">ElevenLabs carries the conversation. n8n coordinates the operation. Supabase keeps the durable record.</p></div><div className="mt-14 grid md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/8 border border-white/8 rounded-[28px] overflow-hidden">{capabilities.map(item=><div key={item.title} className="bg-[#080808] p-7 md:p-8 min-h-60"><item.icon size={20} className="text-gray-400"/><h3 className="text-xl mt-12">{item.title}</h3><p className="text-sm text-gray-500 leading-relaxed mt-3">{item.copy}</p></div>)}</div></div></section>

<section id="trust" className="max-w-7xl mx-auto px-5 md:px-8 py-24 md:py-32 grid lg:grid-cols-2 gap-14 items-center"><div className="relative rounded-[32px] overflow-hidden border border-white/8 min-h-[520px]"><img src="/images/section_character.png" alt="Pandora security and trust" className="absolute inset-0 w-full h-full object-cover grayscale opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent"/><div className="absolute bottom-0 p-8"><p className="text-sm text-gray-400">Security is a product feature.</p><p className="text-3xl font-light mt-2">Every action leaves evidence.</p></div></div><div><p className="eyebrow">Trust by architecture</p><h2 className="section-title">Helpful without being reckless.</h2><div className="mt-8 space-y-5">{['Tenant credentials are encrypted and never sent through n8n or an LLM.','Public callers get Q&A and booking—not access to private operations.','External sends and calendar writes require an exact confirmation.','Audio retention is off by default; redacted transcripts expire after 30 days.'].map(t=><div key={t} className="flex gap-3"><div className="w-6 h-6 rounded-full border border-white/15 flex items-center justify-center shrink-0"><Check size={12}/></div><p className="text-sm text-gray-400 leading-relaxed">{t}</p></div>)}</div></div></section>

<section id="pricing" className="bg-[#080808] border-y border-white/6 py-24 md:py-32"><div className="max-w-7xl mx-auto px-5 md:px-8"><div className="text-center max-w-2xl mx-auto"><p className="eyebrow">Simple NGN pricing</p><h2 className="section-title">Start useful. Pay when Pandora works harder.</h2><p className="section-copy">The free plan is generous on the web. Expensive outbound phone calls use transparent prepaid credit.</p></div><div className="mt-14 grid md:grid-cols-2 xl:grid-cols-4 gap-4">{plans.map(([name,price,copy],i)=><div key={name} className={`rounded-[26px] border p-6 ${i===1?'border-white/25 bg-white/[.04]':'border-white/8 bg-[#0b0b0b]'}`}><p className="text-sm text-gray-400">{name}</p><p className="text-3xl mt-5">{price}<span className="text-xs text-gray-600"> / mo</span></p><p className="text-sm text-gray-500 leading-relaxed mt-5 min-h-20">{copy}</p><Link to="/signup" className={`mt-6 w-full inline-flex justify-center rounded-full px-4 py-3 text-sm font-semibold ${i===1?'bg-white text-black':'border border-white/12 text-white'}`}>{i===0?'Start free':'Choose '+name}</Link></div>)}</div></div></section>

<section className="max-w-5xl mx-auto px-5 md:px-8 py-24 md:py-36 text-center"><p className="eyebrow">Pandora Labs</p><h2 className="text-5xl md:text-7xl font-light tracking-[-.055em]">Give your business<br/>a voice people can reach.</h2><p className="section-copy max-w-xl mx-auto">Start on the web, connect Google Workspace securely, then graduate to phone and messaging channels as your business grows.</p><Link to="/signup" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white text-black px-7 py-4 font-semibold">Create your free workspace <ArrowRight size={16}/></Link></section></main>

<footer className="border-t border-white/6"><div className="max-w-7xl mx-auto px-5 md:px-8 py-8 flex flex-col md:flex-row gap-4 items-center justify-between"><div className="flex items-center gap-2"><PlaceholderLogo size={27}/><span className="text-sm">Pandora Labs</span></div><p className="text-xs text-gray-600">Cloud-powered voice operations for accessible Nigerian business.</p><div className="flex gap-5 text-xs text-gray-500"><a href="mailto:hello@pandoralabs.ai">Contact</a><Link to="/login">Sign in</Link></div></div></footer></div>}

function Proof({value,label}:{value:string;label:string}){return <div><p className="text-sm text-white">{value}</p><p className="text-[11px] text-gray-600 mt-1">{label}</p></div>}
