import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const mutating=new Set(['gmail.send','gmail.trash','calendar.create','calendar.update','calendar.delete']);

async function secureEqual(a:string,b:string){const enc=new TextEncoder();const [ah,bh]=await Promise.all([crypto.subtle.digest('SHA-256',enc.encode(a)),crypto.subtle.digest('SHA-256',enc.encode(b))]);const x=new Uint8Array(ah),y=new Uint8Array(bh);let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}

Deno.serve(async(req)=>{
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const expected=Deno.env.get('PANDORA_CONNECTOR_SERVICE_SECRET');const supplied=req.headers.get('x-pandora-connector-secret')||'';
 if(!expected)return json({error:'Connector broker is not configured'},503);
 if(!supplied||!(await secureEqual(supplied,expected)))return json({error:'Unauthorized'},401);
 try{
  const body=await req.json();const organizationId=String(body.organizationId||'');const operation=String(body.operation||'');const params=body.params&&typeof body.params==='object'?body.params:{};const idempotencyKey=String(body.idempotencyKey||'');
  if(!/^[0-9a-f-]{36}$/i.test(organizationId)||!idempotencyKey||idempotencyKey.length>128)return json({error:'Invalid request'},400);
  const allowed=new Set(['gmail.search','gmail.read','gmail.draft','gmail.send','gmail.trash','calendar.list','calendar.freebusy','calendar.create','calendar.update','calendar.delete']);if(!allowed.has(operation))return json({error:'Operation is not allowed'},400);
  const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
  const {data:org}=await supabase.from('organizations').select('plan_code,status').eq('id',organizationId).single();if(!org||org.status!=='active')return json({error:'Workspace is not active'},403);if(org.plan_code==='free'&&mutating.has(operation))return json({error:'This operation requires a paid plan'},402);
  const {data:prior}=await supabase.from('workflow_events').select('id,redacted_payload').eq('organization_id',organizationId).eq('idempotency_key',`connector:${idempotencyKey}`).maybeSingle();if(prior)return json({ok:true,duplicate:true,result:prior.redacted_payload});
  if(mutating.has(operation)){const approvalId=String(body.approvalId||'');const {data:approval}=await supabase.from('approval_requests').select('id,status,expires_at').eq('id',approvalId).eq('organization_id',organizationId).maybeSingle();if(!approval||approval.status!=='approved'||new Date(approval.expires_at)<=new Date())return json({error:'A current approval is required'},409);}
  const {data:connection}=await supabase.from('integration_connections').select('id,vault_secret_id,status').eq('organization_id',organizationId).eq('provider','google_workspace').eq('status','connected').limit(1).maybeSingle();if(!connection?.vault_secret_id)return json({error:'Google Workspace is not connected'},409);
  const {data:secret,error:secretError}=await supabase.rpc('read_integration_secret',{secret_id:connection.vault_secret_id});if(secretError||!secret)return json({error:'Connected credential is unavailable'},503);let tokens=JSON.parse(String(secret));
  if(!tokens.access_token||Date.now()>=Number(tokens.created_at||0)+Number(tokens.expires_in||0)*1000-60_000){const clientId=Deno.env.get('GOOGLE_CLIENT_ID'),clientSecret=Deno.env.get('GOOGLE_CLIENT_SECRET');if(!clientId||!clientSecret||!tokens.refresh_token)return json({error:'Google reauthorization is required'},409);const refresh=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:tokens.refresh_token,grant_type:'refresh_token'})});const refreshed=await refresh.json();if(!refresh.ok)return json({error:'Google reauthorization is required'},409);tokens={...tokens,...refreshed,created_at:Date.now()};const {data:newSecret}=await supabase.rpc('store_integration_secret',{secret_value:JSON.stringify(tokens),secret_name:`google-workspace-${organizationId}-${crypto.randomUUID()}`,secret_description:'Rotated Google Workspace OAuth tokens'});if(newSecret){await supabase.from('integration_connections').update({vault_secret_id:newSecret,token_expires_at:new Date(Date.now()+Number(tokens.expires_in||3600)*1000).toISOString(),last_checked_at:new Date().toISOString()}).eq('id',connection.id);await supabase.rpc('delete_integration_secret',{secret_id:connection.vault_secret_id});}}
  const result=await executeGoogle(operation,params,tokens.access_token);const correlationId=req.headers.get('x-correlation-id')||crypto.randomUUID();await supabase.from('workflow_events').insert({organization_id:organizationId,workflow_name:'Pandora — Connector Broker',correlation_id:correlationId,event_type:operation.replace('.','_'),status:'success',summary:`Google operation ${operation} completed.`,redacted_payload:sanitize(operation,result),idempotency_key:`connector:${idempotencyKey}`});if(mutating.has(operation)&&body.approvalId)await supabase.from('approval_requests').update({status:'executed'}).eq('id',body.approvalId).eq('status','approved');return json({ok:true,result:sanitize(operation,result)});
 }catch(error){console.error(error);return json({error:'Connector operation failed'},500)}
});

async function executeGoogle(operation:string,p:any,token:string){const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};let url='',method='GET',body:unknown=undefined;
 switch(operation){
  case'gmail.search':url=`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=${Math.min(Number(p.limit||10),25)}&q=${encodeURIComponent(String(p.query||''))}`;break;
  case'gmail.read':url=`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(String(p.messageId))}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject&metadataHeaders=Date`;break;
  case'gmail.draft':url='https://gmail.googleapis.com/gmail/v1/users/me/drafts';method='POST';body={message:{raw:encodeEmail(p)}};break;
  case'gmail.send':url='https://gmail.googleapis.com/gmail/v1/users/me/messages/send';method='POST';body={raw:encodeEmail(p)};break;
  case'gmail.trash':url=`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(String(p.messageId))}/trash`;method='POST';body={};break;
  case'calendar.list':url=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(String(p.calendarId||'primary'))}/events?singleEvents=true&orderBy=startTime&timeMin=${encodeURIComponent(String(p.timeMin))}&timeMax=${encodeURIComponent(String(p.timeMax))}&maxResults=25`;break;
  case'calendar.freebusy':url='https://www.googleapis.com/calendar/v3/freeBusy';method='POST';body={timeMin:p.timeMin,timeMax:p.timeMax,timeZone:p.timeZone,items:[{id:p.calendarId||'primary'}]};break;
  case'calendar.create':url=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(String(p.calendarId||'primary'))}/events?conferenceDataVersion=1&sendUpdates=all`;method='POST';body=calendarEvent(p);break;
  case'calendar.update':url=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(String(p.calendarId||'primary'))}/events/${encodeURIComponent(String(p.eventId))}?conferenceDataVersion=1&sendUpdates=all`;method='PATCH';body=calendarEvent(p);break;
  case'calendar.delete':url=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(String(p.calendarId||'primary'))}/events/${encodeURIComponent(String(p.eventId))}?sendUpdates=all`;method='DELETE';break;
 }
 const response=await fetch(url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();const data=text?JSON.parse(text):{};if(!response.ok)throw new Error(`Google ${operation} failed: ${response.status}`);return data;
}
function encodeEmail(p:any){const to=String(p.to||'').replace(/[\r\n]/g,'');const subject=String(p.subject||'').replace(/[\r\n]/g,'');const content=`To: ${to}\r\nSubject: ${subject}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${String(p.body||'')}`;return btoa(unescape(encodeURIComponent(content))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function calendarEvent(p:any){return{summary:String(p.title||''),description:String(p.description||''),start:{dateTime:String(p.start),timeZone:String(p.timeZone||'Africa/Lagos')},end:{dateTime:String(p.end),timeZone:String(p.timeZone||'Africa/Lagos')},attendees:Array.isArray(p.attendees)?p.attendees.map((email:string)=>({email})):[],conferenceData:p.createMeet?{createRequest:{requestId:crypto.randomUUID(),conferenceSolutionKey:{type:'hangoutsMeet'}}}:undefined}}
function sanitize(operation:string,result:any){if(operation==='gmail.read')return{id:result.id,threadId:result.threadId,snippet:result.snippet,payload:{headers:result.payload?.headers||[]}};if(operation.startsWith('gmail.'))return{id:result.id||result.message?.id,threadId:result.threadId||result.message?.threadId};if(operation.startsWith('calendar.'))return{id:result.id,summary:result.summary,start:result.start,end:result.end,htmlLink:result.htmlLink,hangoutLink:result.hangoutLink,calendars:result.calendars,items:result.items?.slice?.(0,25)};return{ok:true}}
